name: continuous_deployment

on:
  workflow_run:
    workflows:
      - continuous_integration
    types: 
      - completed
  push:
    paths: 
       - 'Chatter.IntegrationEventRelay.Core/**'

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY_INTEGRATIONEVENTRELAY }}
      NUGET_URL: https://api.nuget.org/v3/index.json
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          source-url: ${{ env.NUGET_URL }}
      - name: Download Source
        uses: dawidd6/action-download-artifact@v2.16.0
        id: download-source
        with:
          name: source
          path: ./dist/source
          workflow: ci.yml
      
      - name: Download NuGet
        uses: dawidd6/action-download-artifact@v2.16.0
        id: download-nuget
        with:
          name: nuget
          path: ./dist/nuget
          workflow: ci.yml
      
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./dist
        
      - name: Push Nuget packages
        shell: bash
        run: |
          dotnet nuget push "./dist/nuget/*.nupkg" -k '${{ env.NUGET_AUTH_TOKEN }}' -s '${{ env.NUGET_URL }}'
