name: Build

on:
  push:
    branches:
    - feature/*
    - release/*
    - bugfix/*
    - hotfix/*
  pull_request:
    branches:
    - main
    - release/*
    - hotfix/*

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      dotnet-version:  '6.0.x'

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish Chatter.IntegrationEventRelay.Core/src/Chatter.IntegrationEventRelay.Core.csproj -c Release -o publish
    - name: Create nupkg
      run: dotnet pack Chatter.IntegrationEventRelay.Core/src/Chatter.IntegrationEventRelay.Core.csproj -c Release -o publish
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: Chatter.IntegrationEventRelay.Core
        path: /home/runner/work/Chatter.IntegrationEventRelay/Chatter.IntegrationEventRelay/publish/**
        if-no-files-found: error
