name: continuous_integration

on:
  workflow_dispatch:
  push:
    branches:
    - feature/**
    - release/**
    - bugfix/**
    - hotfix/**
  pull_request:
    branches:
    - main
    - release/**

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      dotnet-version:  '6.0.x'

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish Chatter.IntegrationEventRelay.Core/src/Chatter.IntegrationEventRelay.Core.csproj -c Release -o publish/source
    - name: Create nupkg
      run: dotnet pack Chatter.IntegrationEventRelay.Core/src/Chatter.IntegrationEventRelay.Core.csproj -c Release -o publish/nuget
    - name: Upload Source
      uses: actions/upload-artifact@v2.3.1
      with:
        name: source
        path: /home/runner/work/Chatter.IntegrationEventRelay/Chatter.IntegrationEventRelay/publish/source/**
        retention-days: 5
        if-no-files-found: error
    - name: Upload NuGet
      uses: actions/upload-artifact@v2.3.1
      with:
        name: nuget
        path: /home/runner/work/Chatter.IntegrationEventRelay/Chatter.IntegrationEventRelay/publish/nuget/**
        retention-days: 5
        if-no-files-found: error
